name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.120.4'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Cache Hugo build resources
        id: cache-hugo
        uses: actions/cache@v3
        with:
          path: resources
          key: hugo-resources-v1

      - name: Build
        run: hugo --gc --minify -F

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
